### ISSUE TITLE
[Dataset submission/request]: **Carbon allotrope of multilayer graphene and graphite**

### ISSUE THREAD

**Issue by mjwen** [gpwolfe/colabfit-data#57]
### Name

Mingjian Wen

### Email

mjwen@central.uh.edu

### Dataset name

C_WenTadmor_2019

### Authors

Mingjian Wen, Ellad B. Tadmor

### Publication link

https://journals.aps.org/prb/abstract/10.1103/PhysRevB.100.195419

### Data link

https://journals.aps.org/prb/abstract/10.1103/PhysRevB.100.195419#supplemental

### Dataset description

The dataset consists of energies and forces for pristine and defected monolayer graphene, bilayer graphene, and graphite in various states. The configurations in the dataset are generated in two ways: (1) crystals with distortions (compression and stretching of the simulation cell together with random perturbations of atoms), and (2) configura- tions drawn from ab initio molecular dynamics (AIMD) trajectories at 300, 900, and 1500 K.

### pristine
- In-plane compressed and stretched monolayers 
- AIMD trajectories

### defected
- Configurations from the minimization of a monolayer with a single vacancy
- AIMD trajectories of monolayers with a single vacancy 

### pristine
- AB-stacked bilayers with compression and stretching in the basal plane
- Bilayers with different translational registry (e.g. AA, AB, and SP) at various layer separations 
- Twisted bilayers with different twisting angles at various layer separations
- AIMD trajectories of twisted bilayers and bilayers in AB and AA stackings

### defected
- Configurations from the minimization of a bilayer with a single vacancy in each layer
- AIMD trajectories of a bilayer with a single vacancy in one layer and the other layer pristine
- AIMD trajectories of a bilayer with a single vacancy in each layer; Initial configuration without interlayer bonds
- AIMD trajectories of a bilayer with a single vacancy in each layer; Initial configuration with interlayer bonds formed

### pristine 
- Graphite with compression and stretching in the basal plane 
-  Graphite with compression and stretching along the c-axis
- AIMD trajectories

### File details

The dataset are provided as extended xyz files, which can be accessed via the supplemental material of the linked paper. 

### Method

DFT-PBE

### Software

VASP

### Software version(s)

5.x.x

### Additional details

XC Functional: PBE
van den Waals correction: MBD (many-body correction),  Phys. Rev. Lett. 108, 236402 (2012) 
Plane wave basis energy cutoff: 500eV

### Property types

Atomic forces, Potential energy

### Energy field conjugate with forces

potential energy 

### Property details

potential-energy: units=eV, per-atom=False
coordinates: units=Angstrom
atomic-forces: units=eV/Angstrom

### Elements

C

### Number of Configurations

13500

### Permissions

- [X] I confirm that I have the necessary permissions to submit this dataset

**Comment by gpwolfe** [comment]
Now ingested to ColabFit

**Comment by mjwen** [comment]
Thanks! @gpwolfe
